env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:n/recommended'
  - 'prettier'
plugins:
  - import
parserOptions:
  ecmaVersion: 2020
rules:
  no-console: error
  prefer-const: error
  no-var: error
  no-use-before-define: error
  no-await-in-loop: error
  n/exports-style: [0, error]
  n/no-extraneous-import:
    - error
    - allowModules: [nunjucks]
  import/first: error
  import/no-anonymous-default-export: error
  import/no-unassigned-import: error
  import/no-internal-modules:
    - error
    - allow:
        - metalsmith/**
